### ISSUE TITLE
Raytracing example

### ISSUE THREAD

**Issue by ib00** [bqqbarbhg/guppy#7]
OpenCL raytracing example on linux produces wrong result.
CPU and CUDA results match.

![out_cpu](https://github.com/bqqbarbhg/guppy/assets/59011747/81c326a3-998e-409f-9889-607ba0b387b4)

![out_opencl](https://github.com/bqqbarbhg/guppy/assets/59011747/a638169d-c43d-48eb-9400-2a7ee8653d0f)

**Comment by bqqbarbhg** [comment]
Interesting, looks like the framebuffer does not get cleared, need to see if I can repro this.

**Comment by bqqbarbhg** [comment]
Turns out it was using uninitialized memory in the form of `hit.normal`, fixed in 0690624

**Comment by ib00** [comment]
Thank you!
